CREATE DATABASE HOSPITAL_DB;
USE HOSPITAL_DB;

CREATE TABLE patients (
    patient_id INT PRIMARY KEY,
    patient_name VARCHAR(50),
    gender VARCHAR(10),
    age INT,
    city VARCHAR(50)
);

INSERT INTO patients VALUES
(1,'Amit','Male',25,'Mumbai'),
(2,'Priya','Female',30,'Pune'),
(3,'Rahul','Male',45,'Nagpur'),
(4,'Sneha','Female',28,'Hyderabad'),
(5,'Karan','Male',35,'Delhi'),
(6,'Anjali','Female',40,'Pune'),
(7,'Rohit','Male',32,'Mumbai'),
(8,'Pooja','Female',29,'Bangalore'),
(9,'Vikas','Male',50,'Chennai'),
(10,'Neha','Female',27,'Hyderabad');

SELECT * FROM PATIENTS;

CREATE TABLE doctors (
    doctor_id INT PRIMARY KEY,
    doctor_name VARCHAR(50),
    specialization VARCHAR(50)
);

INSERT INTO doctors VALUES
(101,'Dr. Sharma','Cardiologist'),
(102,'Dr. Mehta','Dermatologist'),
(103,'Dr. Rao','Orthopedic'),
(104,'Dr. Patel','Neurologist'),
(105,'Dr. Khan','General Physician');

SELECT * FROM DOCTORS;

CREATE TABLE appointments (
    appointment_id INT PRIMARY KEY,
    patient_id INT,
    doctor_id INT,
    appointment_date DATE,
    consultation_fee DECIMAL(10,2),
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
);

INSERT INTO appointments VALUES
(1,1,101,'2025-01-05',1000),
(2,2,102,'2025-01-08',800),
(3,3,103,'2025-01-10',1200),
(4,4,104,'2025-01-12',1500),
(5,5,105,'2025-01-15',700),
(6,6,101,'2025-01-18',1000),
(7,7,102,'2025-01-20',800),
(8,8,103,'2025-01-22',1200),
(9,9,104,'2025-01-25',1500),
(10,10,105,'2025-01-28',700),
(11,1,105,'2025-02-02',700),
(12,2,101,'2025-02-05',1000),
(13,3,104,'2025-02-10',1500),
(14,4,102,'2025-02-15',800),
(15,5,103,'2025-02-18',1200);

SELECT * FROM APPOINTMENTS;

SELECT PATIENT_NAME, CITY
FROM PATIENTS;

SELECT DOCTOR_NAME, specialization
FROM DOCTORS
WHERE SPECIALIZATION = "Cardiologist";

SELECT *
FROM APPOINTMENTS
WHERE appointment_date > "2025-01-15";

SELECT SUM(consultation_fee) AS TOTAL_CONSULTATION_FEE
FROM APPOINTMENTS;

SELECT AVG(consultation_fee) AS AVG_CONSULTATION_FEE
FROM APPOINTMENTS;

SELECT MAX(CONSULTATION_FEE) AS MAX_CONSULTAION_FEE
FROM APPOINTMENTS;

SELECT MIN(CONSULTATION_FEE) AS MIN_CONSULTAION_FEE
FROM APPOINTMENTS;

SELECT COUNT(APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM APPOINTMENTS;

SELECT DOCTOR_NAME, COUNT(APPOINTMENT_ID) AS APPOINMENTS_OF_DOCTORS
FROM DOCTORS
INNER JOIN APPOINTMENTS
ON DOCTORS.DOCTOR_ID = APPOINTMENTS.DOCTOR_ID
GROUP BY DOCTOR_NAME;

SELECT DOCTOR_NAME, SUM(consultation_fee) AS TOTAL_CONSULTATION_FEES
FROM DOCTORS
INNER JOIN APPOINTMENTS
ON DOCTORS.DOCTOR_ID = APPOINTMENTS.DOCTOR_ID
GROUP BY DOCTOR_NAME;

select CITY, COUNT(PATIENT_ID)
FROM PATIENTS
GROUP BY CITY;

SELECT DOCTOR_NAME, AVG(CONSULTATION_FEE) AS AVG_CONSLT_FEE
FROM DOCTORS
INNER JOIN APPOINTMENTS
ON DOCTORS.DOCTOR_ID = APPOINTMENTS.DOCTOR_ID
GROUP BY DOCTOR_NAME;

SELECT MONTH(APPOINTMENT_DATE) AS MONTH, 
       COUNT(APPOINTMENT_ID) AS APPOINTMENT_COUNT
  FROM APPOINTMENTS
  GROUP BY MONTH(APPOINTMENT_DATE)
  ORDER BY MONTH;

SELECT PATIENT_NAME, APPOINTMENT_DATE
FROM PATIENTS
INNER JOIN APPOINTMENTS
ON PATIENTS.PATIENT_ID = APPOINTMENTS.PATIENT_ID;

SELECT DOCTOR_NAME, CONSULTATION_FEE
FROM DOCTORS
INNER JOIN APPOINTMENTS
ON DOCTORS.DOCTOR_ID = APPOINTMENTS.DOCTOR_ID;

SELECT PATIENT_NAME, DOCTOR_NAME, APPOINTMENT_DATE
FROM PATIENTS
INNER JOIN APPOINTMENTS
ON PATIENTS.PATIENT_ID = APPOINTMENTS.PATIENT_ID
INNER JOIN DOCTORS
ON DOCTORS.DOCTOR_ID = APPOINTMENTS.DOCTOR_ID;

SELECT DOCTOR_NAME, SUM(consultation_fee) AS TOTAL_REVENUE
FROM DOCTORS
INNER JOIN APPOINTMENTS
ON DOCTORS.DOCTOR_ID = APPOINTMENTS.DOCTOR_ID
GROUP BY DOCTOR_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

SELECT PATIENT_NAME, COUNT(APPOINTMENT_DATE) AS TOTAL_VISIT
FROM PATIENTS
INNER JOIN APPOINTMENTS
ON PATIENTS.PATIENT_ID = APPOINTMENTS.PATIENT_ID
GROUP BY PATIENT_NAME
ORDER BY TOTAL_VISIT DESC
LIMIT 1;

