create database Bank_management_system;
use Bank_management_system;

CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(50),
CITY VARCHAR(50),
ACCOUNT_TYPE VARCHAR(20)
);

INSERT INTO customers VALUES
(1,'Neha','Hyderabad','Savings'),
(2,'Rahul','Mumbai','Current'),
(3,'Priya','Pune','Savings'),
(4,'Amit','Delhi','Current'),
(5,'Sneha','Bangalore','Savings');

SELECT * FROM CUSTOMERS;

CREATE TABLE ACCOUNTS (
ACCOUNT_ID INT PRIMARY KEY,
CUSTOMER_ID INT,
BALANCE DECIMAL(10, 2),
ACCOUNT_OPEN_DATE DATE
);

INSERT INTO accounts VALUES
(101,1,50000,'2023-01-10'),
(102,2,75000,'2022-06-15'),
(103,3,60000,'2023-03-20'),
(104,4,90000,'2021-08-05'),
(105,5,45000,'2024-01-12');

SELECT * FROM ACCOUNTS;

CREATE TABLE TRANSATIONS (
TRANSACTION_ID INT PRIMARY KEY,
ACCOUNT_ID INT,
TRANSACTION_TYPE VARCHAR(20),
AMOUNT DECIMAL (10,2),
TRANSACTION_DATE DATE
);

INSERT INTO TRANSATIONS VALUES
(1,101,'Deposit',10000,'2025-01-10'),
(2,102,'Withdrawal',5000,'2025-01-15'),
(3,103,'Deposit',15000,'2025-02-01'),
(4,104,'Withdrawal',10000,'2025-02-05'),
(5,105,'Deposit',8000,'2025-02-10'),
(6,101,'Withdrawal',3000,'2025-02-12'),
(7,102,'Deposit',12000,'2025-02-15'),
(8,103,'Withdrawal',4000,'2025-02-18'),
(9,104,'Deposit',20000,'2025-02-20'),
(10,105,'Withdrawal',2000,'2025-02-25');

SELECT * FROM TRANSATIONS;

SELECT CUSTOMER_NAME, CITY 
FROM CUSTOMERS
WHERE CITY = "HYDERABAD";

SELECT CUSTOMER_NAME, ACCOUNT_TYPE
FROM CUSTOMERS
WHERE ACCOUNT_TYPE = "SAVINGS";

SELECT SUM(BALANCE)
FROM ACCOUNTS;

SELECT AVG(BALANCE)
FROM ACCOUNTS;

SELECT MAX(BALANCE)
FROM ACCOUNTS;

SELECT MIN(BALANCE)
FROM ACCOUNTS;

SELECT COUNT(customer_NAME)
FROM customerS;

SELECT ACCOUNT_TYPE, COUNT(CUSTOMER_NAME)
FROM CUSTOMERS
GROUP BY ACCOUNT_TYPE; 

SELECT TRANSACTION_TYPE, SUM(AMOUNT)
FROM TRANSATIONS
GROUP BY TRANSACTION_TYPE;

SELECT ACCOUNT_TYPE, SUM(BALANCE) AS TOTAL_BALANCE
FROM CUSTOMERS
INNER JOIN ACCOUNTS
ON CUSTOMERS.CUSTOMER_ID = ACCOUNTS.CUSTOMER_ID
GROUP BY ACCOUNT_TYPE;

SELECT CUSTOMER_NAME, BALANCE
FROM CUSTOMERS
INNER JOIN ACCOUNTS
ON CUSTOMERS.CUSTOMER_ID = ACCOUNTS.CUSTOMER_ID;

SELECT ACCOUNT_ID, CUSTOMER_NAME
FROM ACCOUNTS
INNER JOIN CUSTOMERS
ON ACCOUNTS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;

SELECT CUSTOMER_NAME, TRANSACTION_ID,
TRANSACTION_TYPE,
AMOUNT,
TRANSACTION_DATE 
FROM CUSTOMERS
INNER JOIN ACCOUNTS
ON CUSTOMERS.CUSTOMER_ID = ACCOUNTS.CUSTOMER_ID
INNER JOIN TRANSATIONS
ON ACCOUNTS.ACCOUNT_ID = TRANSATIONS.ACCOUNT_ID;

SELECT CUSTOMER_NAME, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM CUSTOMERS
INNER JOIN ACCOUNTS
ON CUSTOMERS.CUSTOMER_ID = ACCOUNTS.CUSTOMER_ID
INNER JOIN TRANSATIONS
ON TRANSATIONS.ACCOUNT_ID = ACCOUNTS.ACCOUNT_ID
GROUP BY CUSTOMER_NAME;

SELECT CUSTOMER_NAME, BALANCE
FROM customerS
INNER JOIN ACCOUNTS
ON CUSTOMERS. CUSTOMER_ID = ACCOUNTS.CUSTOMER_ID
WHERE BALANCE >60000;

SELECT CUSTOMER_NAME AS DEPOSITE_PEOPLE, TRANSACTION_TYPE
FROM CUSTOMERS
INNER JOIN ACCOUNTS
ON CUSTOMERS.CUSTOMER_ID = ACCOUNTS.CUSTOMER_ID
INNER JOIN TRANSATIONS
ON ACCOUNTS.ACCOUNT_ID = TRANSATIONS.ACCOUNT_ID
WHERE TRANSACTION_TYPE = "DEPOSIT";

SELECT CUSTOMER_NAME, BALANCE
FROM CUSTOMERS
INNER JOIN ACCOUNTS
ON CUSTOMERS.CUSTOMER_ID = ACCOUNTS.CUSTOMER_ID
ORDER BY BALANCE DESC
LIMIT 1;
